before_script:
  - echo 'before_script'

after_script:
  - echo 'after_script'

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - echo 'stage build' && ./ci-test 
  only:
    - master
  tags:
    - docker


